AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a simple ECS Fargate task and schedule it hourly via EventBridge.

Parameters:
  ClusterName:
    Type: String
    Description: Name of the existing ECS cluster
  SubnetIds:
    Type: CommaDelimitedList
    Description: Comma-separated list of subnet IDs
  SecurityGroupIds:
    Type: CommaDelimitedList
    Description: Comma-separated list of security group IDs
  ImageUri:
    Type: String
    Description: Full ECR image URI (repo:tag)

Resources:
  MyAppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${AWS::StackName}"
      RetentionInDays: 7

  MyAppExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  MyAppTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${AWS::StackName}-task"
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt MyAppExecutionRole.Arn
      ContainerDefinitions:
        - Name: myapp
          Image: !Ref ImageUri
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${AWS::StackName}"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  MyAppEventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 hour)
      State: ENABLED
      Targets:
        - Arn: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ClusterName}"
          Id: MyAppEcsTarget
          RoleArn: !GetAtt MyAppExecutionRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref MyAppTaskDefinition
            LaunchType: FARGATE
          NetworkConfiguration:     # ✅ moved outside EcsParameters
            AwsvpcConfiguration:
              Subnets: !Ref SubnetIds
              SecurityGroups: !Ref SecurityGroupIds
              AssignPublicIp: ENABLED

Outputs:
  TaskDefinitionArn:
    Description: ARN of the ECS task definition
    Value: !Ref MyAppTaskDefinition
  LogGroupName:
    Description: CloudWatch LogGroup for the app
    Value: !Sub "/ecs/${AWS::StackName}"
  EventRuleName:
    Description: Name of the EventBridge rule
    Value: !Ref MyAppEventRule
