AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy simple ECS Fargate task and schedule

Parameters:
  ClusterName:
    Type: String
  SubnetIds:
    Type: CommaDelimitedList
  SecurityGroupIds:
    Type: CommaDelimitedList
  ImageUri:
    Type: String

Resources:
  MyAppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${AWS::StackName}"
      RetentionInDays: 7

  MyAppExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  MyAppTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${AWS::StackName}-task"
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt MyAppExecutionRole.Arn
      ContainerDefinitions:
        - Name: myapp
          Image: !Ref ImageUri
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${AWS::StackName}"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          Essential: true

  MyAppEventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 hour)
      State: ENABLED
      Targets:
        - Arn: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ClusterName}"
          Id: MyAppEcsTarget
          RoleArn: !GetAtt MyAppExecutionRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref MyAppTaskDefinition
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsvpcConfiguration:
                Subnets: !Ref SubnetIds
                SecurityGroups: !Ref SecurityGroupIds
                AssignPublicIp: ENABLED
